# Generated by Django 5.1.4 on 2024-12-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0002_motionevent_delete_motiondetection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motionevent",
            name="motion_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
